#Fungsi Normalisasi dan Inisialisasi data

In [35]:
import numpy as np

#normalisasi
def min_max(data, min_val, max_val):
  data = np.array(data, dtype=float)
  if max_val - min_val == 0:
    return data

  scaled_data = (data - min_val) / (max_val - min_val)
  return scaled_data

y1 = 0.92
y2 = 0.7
y3 = 0.85
y = [y1, y2, y3]

x = np.array([[30, 9, 90],
             [20, 9, 80],
             [25, 3, 90],
             [27, 6, 85]])

data1 = x[:,0]
data1_norm = min_max(data1, 0, 40) #data min dan max sesuai yang diberikan di kelas

print(f"Data awal: {data1}")
print(f"Normalized: {data1_norm}")

data2 = x[:,1]
data2_norm = min_max(data2, 0, 15)
print(f"\nData awal: {data2}")
print(f"Normalized: {data2_norm}")

data3 = x[:,2]
data3_norm = min_max(data3, 0, 100)
print(f"\nData awal: {data3}")
print(f"Normalized: {data3_norm}")

#Setelah normalisasi:
#              a      b    c   y
#             0.75  0.6  0.9  0.92
#             0.5   0.6  0.8  0.7
#             0.625 0.2  0.9  0.85
# x_dicari :  0.675 0.4  0.85 ...

a = data1_norm[:3]
b = data2_norm[:3]
c = data3_norm[:3]
x_dicari = np.array([data1_norm[3], data2_norm[3], data3_norm[3]])

print(a)
print(b)
print(c)
print(x_dicari)

Data awal: [30 20 25 27]
Normalized: [0.75  0.5   0.625 0.675]

Data awal: [9 9 3 6]
Normalized: [0.6 0.6 0.2 0.4]

Data awal: [90 80 90 85]
Normalized: [0.9  0.8  0.9  0.85]
[0.75  0.5   0.625]
[0.6 0.6 0.2]
[0.9 0.8 0.9]
[0.675 0.4   0.85 ]


#Gradient Descent

In [40]:
#asumsi
max_it = 1000
weight = np.array([0, 0, 0])
bias = 0
alpha = 0.01 #learning rate

for iterasi in range(max_it):
  y_pred1 = a[0]*weight[0] + b[0]*weight[1] + c[0]*weight[2] + bias
  y_pred2 = a[1]*weight[0] + b[1]*weight[1] + c[1]*weight[2] + bias
  y_pred3 = a[2]*weight[0] + b[2]*weight[1] + c[2]*weight[2] + bias
  y_pred = np.array([y_pred1, y_pred2, y_pred3])
  loss = np.sum((y - y_pred) ** 2)

  dw1 = 2*((y_pred - y).dot(a))
  dw2 = 2*((y_pred - y).dot(b))
  dw3 = 2*((y_pred - y).dot(c))

  dw = np.array([dw1, dw2, dw3])
  db = 2*np.sum(y_pred - y)

  weight = weight - alpha*dw
  bias = bias - alpha*db

  if loss < 0.00001: #selesaikan iterasi jika error mendekati 0
    break

  if iterasi <= 10 or iterasi % 100 == 0:
    print(f"\nIterasi ke-{iterasi}:")
    print(f"Loss: {loss}")
    print(f"Weight: {weight}")
    print(f"Bias: {bias}")
    print(f"Prediksi y: {y_pred}")

y_pred_dicari = x_dicari.dot(weight) + bias

print(f"\nWeight Akhir: {weight}")
print(f"Bias Akhir: {bias}")
print(f"Prediksi akhir:", y_pred_dicari)
print(f"loss: ", loss)


Iterasi ke-0:
Loss: 2.0589
Weight: [0.031425 0.02284  0.04306 ]
Bias: 0.049400000000000006
Prediksi y: [0. 0. 0.]

Iterasi ke-1:
Loss: 1.519714093572703
Weight: [0.05843142 0.04236625 0.08002756]
Bias: 0.0917789225
Prediksi y: [0.12542675 0.1132645  0.11236263]

Iterasi ke-2:
Loss: 1.1227186306880774
Weight: [0.08164639 0.05904927 0.11176739]
Bias: 0.12813332065784375
Prediksi y: [0.23304704 0.21043643 0.20879661]

Iterasi ke-3:
Loss: 0.830413573237571
Weight: [0.10160803 0.07329276 0.13902147]
Bias: 0.15931829791059293
Prediksi y: [0.32538833 0.29379999 0.29156282]

Iterasi ke-4:
Loss: 0.6151888175203257
Weight: [0.11877808 0.08544314 0.16242646]
Bias: 0.18606758520633593
Prediksi y: [0.4046193  0.36531514 0.36260119]

Iterasi ke-5:
Loss: 0.45671590878792667
Weight: [0.13355272 0.09579766 0.18252865]
Bias: 0.20901076849379446
Prediksi y: [0.47260084 0.42666367 0.42357632]

Iterasi ke-6:
Loss: 0.3400276423551416
Weight: [0.14627194 0.10461137 0.1997968 ]
Bias: 0.22868807095928637
Pred

#Steepest Descent

In [41]:
#asumsi awal:
max_it = 1000
weight = np.array([0, 0, 0])
bias = 0

def get_learning_rate(a, b, c, dw, bias, y):
  dw1 = dw[0]
  dw2 = dw[1]
  dw3 = dw[2]
  j = dw1*a + dw2*b + dw3*c + db

  numerator = np.sum((weight[0]*a + weight[1]*b + weight[2]*c + bias - y) * j)
  denominator = np.sum((dw1*a + dw2*b +dw3*c +db) * j)

  if denominator != 0:
    alpha = numerator / denominator
  else:
    alpha = 0.001

  return alpha


for iterasi in range(max_it):
  y_pred1 = a[0]*weight[0] + b[0]*weight[1] + c[0]*weight[2] + bias
  y_pred2 = a[1]*weight[0] + b[1]*weight[1] + c[1]*weight[2] + bias
  y_pred3 = a[2]*weight[0] + b[2]*weight[1] + c[2]*weight[2] + bias
  y_pred = np.array([y_pred1, y_pred2, y_pred3])
  loss = np.sum((y - y_pred) ** 2)

  dw1 = 2*((y_pred - y).dot(a))
  dw2 = 2*((y_pred - y).dot(b))
  dw3 = 2*((y_pred - y).dot(c))

  dw = np.array([dw1, dw2, dw3])
  db = 2*np.sum(y_pred - y)

  alpha = get_learning_rate(a, b, c, dw, bias, y)

  weight = weight - alpha*dw
  bias = bias - alpha*db

  if loss < 0.00001:
    break

  if iterasi <= 10 or iterasi % 100 == 0:
    print(f"\nIterasi ke-{iterasi}:")
    print(f"Loss: {loss}")
    print(f"Weight: {weight}")
    print(f"Bias: {bias}")
    print(f"Prediksi y: {y_pred}")

y_pred_dicari = x_dicari.dot(weight) + bias

print(f"\nWeight Akhir: {weight}")
print(f"Bias Akhir: {bias}")
print(f"Prediksi akhir:", y_pred_dicari)
print(f"loss: ", loss)


Iterasi ke-0:
Loss: 2.0589
Weight: [0.22141208 0.16092448 0.30338915]
Bias: 0.34805908536771063
Prediksi y: [0. 0. 0.]

Iterasi ke-1:
Loss: 0.014327718603290053
Weight: [ 0.38292529 -0.1190836   0.37745276]
Bias: 0.31021806107470334
Prediksi y: [0.88372307 0.79803114 0.79167677]

Iterasi ke-2:
Loss: 0.004226497848833887
Weight: [ 0.38566432 -0.11722234  0.37914144]
Bias: 0.31144135839186965
Prediksi y: [0.86566935 0.73219275 0.86543713]

Iterasi ke-3:
Loss: 0.004142609600338188
Weight: [ 0.38869953 -0.11562323  0.37644165]
Bias: 0.305939155709929
Prediksi y: [0.87158349 0.73725326 0.87026438]

Iterasi ke-4:
Loss: 0.00406100878561044
Weight: [ 0.39138481 -0.1138491   0.37809448]
Bias: 0.3071250643311322
Prediksi y: [0.86688735 0.7320683  0.8645492 ]

Iterasi ke-5:
Loss: 0.003981612588625812
Weight: [ 0.39440516 -0.1124126   0.37549841]
Bias: 0.3017552230807281
Prediksi y: [0.87263924 0.73698359 0.86925578]

Iterasi ke-6:
Loss: 0.0039042972589214296
Weight: [ 0.3970388  -0.11071918  0.3